### PR TITLE
Fix table name

### PR DESCRIPTION
**Pull request by jenky**

### CODE REVIEW

**Comment by antonkomarev** [comment]
@jenky Thank you for the PR. Internally in our company we are using singular table names. So we have table `user` instead default Laravel `users` table. I think it will be better comment out foreign keys to let people decide if they want to use them - remove comments and modify table name.

**Comment by antonkomarev** [comment]
If you will just comment out this string I will accept PR.

```php
// $table->foreign('user_id')->references('id')->on('user')->onDelete('cascade');
```

**Comment by jenky** [comment]
I can use the `getTable` method  from the model, but the `User` model namespace would be different for each app. So I think create a config file with user model option would be great just like `config.services.stripe.model`

**Comment by antonkomarev** [comment]
I'd prefer not to add config file just to setup user model which will be used only in migrations at this moment. Let's just comment out foreign key constraint for now at least because not all developers are using them.

**Comment by antonkomarev** [comment]
@jenky thanks that pointed out on this issue. This changes will be in today minor release.

**Pull request closed without merging**
